### ISSUE TITLE
Wrong warning on Attribute

### ISSUE THREAD

**Issue by dscopra** [BADF00D/SwitchToNUnit3#13]
I got a message "Reference to TestCaseSoruce has to be static", that make no sense at the current location:

![image](https://user-images.githubusercontent.com/13195823/32098570-719b2e54-bb0d-11e7-972f-83a4a1282c93.png)

**Comment by dscopra** [comment]
![xmlelement](https://user-images.githubusercontent.com/13195823/32263213-0a38ff6e-bed9-11e7-9cae-0d7703198019.png)

**Comment by BADF00D** [comment]
The problem is, the algorithm does not check what type the argument is of.

**Comment by BADF00D** [comment]
Fixed in release 0.3
